-- Alimentar la base de datos

-- 1. Tablas catálogo
CREATE TABLE genero (
    ID_GENERO INT PRIMARY KEY,
    GENERO NVARCHAR(20) NOT NULL
);

CREATE TABLE score_crediticio (
    ID_SCORE_CREDITICIO INT PRIMARY KEY,
    SCORE_CREDITICIO NVARCHAR(50) NOT NULL
);

CREATE TABLE tipo_financiacion (
    ID_TIPO_FINANCIACION INT PRIMARY KEY,
    TIPO_FINANCIACION NVARCHAR(50) NOT NULL
);

CREATE TABLE canal (
    ID_CANAL_DESEMBOLSO NVARCHAR(10) PRIMARY KEY,
    CANAL_DESEMBOLSO NVARCHAR(50) NOT NULL
);

CREATE TABLE canal_solicitud (
    ID_CANAL_SOLICITUD INT PRIMARY KEY,
    CANAL_SOLICITUD NVARCHAR(30) NOT NULL
);

CREATE TABLE estado_credito (
    ID_ESTADO_CREDITO INT PRIMARY KEY,
    ESTADO_CREDITO NVARCHAR(20) NOT NULL
);

CREATE TABLE producto (
    ID_PRODUCTO NVARCHAR(10) PRIMARY KEY,
    PRODUCTO NVARCHAR(100) NOT NULL
);

CREATE TABLE unidad_geografica (
    ID_PROVINCIA INT PRIMARY KEY,
    PROVINCIA NVARCHAR(100) NOT NULL,
    PAIS NVARCHAR(50) NOT NULL
);

CREATE TABLE ciudad (
    ID_CIUDAD INT PRIMARY KEY,
    CIUDAD NVARCHAR(100) NOT NULL,
    LATITUD DECIMAL(8,4),
    LONGITUD DECIMAL(8,4)
);

-- 2. Tabla clientes (depende de catálogos)
CREATE TABLE clientes (
    ID_CLIENTE INT PRIMARY KEY,
    ID_SCORE_CREDITICIO INT NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDO NVARCHAR(50) NOT NULL,
    CORREO_ELECTRONICO NVARCHAR(100),
    FECHA_NACIMIENTO DATE,
    ID_GENERO INT NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    ID_CIUDAD INT NOT NULL,
    CONSTRAINT FK_CLIENTE_SCORE FOREIGN KEY (ID_SCORE_CREDITICIO) REFERENCES score_crediticio(ID_SCORE_CREDITICIO),
    CONSTRAINT FK_CLIENTE_GENERO FOREIGN KEY (ID_GENERO) REFERENCES genero(ID_GENERO),
    CONSTRAINT FK_CLIENTE_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES unidad_geografica(ID_PROVINCIA),
    CONSTRAINT FK_CLIENTE_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES ciudad(ID_CIUDAD)
);

-- 3. Tabla cuenta_prestamo (depende de clientes y catálogos)
CREATE TABLE cuenta_prestamo (
    ID_CUENTA INT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    MONTO DECIMAL(12,2) NOT NULL,
    CUOTAS INT NOT NULL,
    NRO_COMPROBANTE BIGINT,
    ID_PRODUCTO NVARCHAR(10) NOT NULL,
    ID_CANAL_DESEMBOLSO NVARCHAR(10) NOT NULL,
    ID_TIPO_FINANCIACION INT NOT NULL,
    DIAS_MORA INT,
    ID_ESTADO_CREDITO INT NOT NULL,
    ID_CANAL_SOLICITUD INT NOT NULL,
    FECHA_OTORGAMIENTO DATE,
    CONSTRAINT FK_PRESTAMO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES clientes(ID_CLIENTE),
    CONSTRAINT FK_PRESTAMO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES producto(ID_PRODUCTO),
    CONSTRAINT FK_PRESTAMO_CANAL FOREIGN KEY (ID_CANAL_DESEMBOLSO) REFERENCES canal(ID_CANAL_DESEMBOLSO),
    CONSTRAINT FK_PRESTAMO_FINANCIACION FOREIGN KEY (ID_TIPO_FINANCIACION) REFERENCES tipo_financiacion(ID_TIPO_FINANCIACION),
    CONSTRAINT FK_PRESTAMO_ESTADO FOREIGN KEY (ID_ESTADO_CREDITO) REFERENCES estado_credito(ID_ESTADO_CREDITO),
    CONSTRAINT FK_PRESTAMO_SOLICITUD FOREIGN KEY (ID_CANAL_SOLICITUD) REFERENCES canal_solicitud(ID_CANAL_SOLICITUD)
);
